### ISSUE TITLE
Add opcion for assister player

### ISSUE THREAD

**Issue by ramonberrutti** [abnerfs/killfeed_filter#1]
They will be nice, to show also the feed to the assister!!

Thanks.

**Comment by ramonberrutti** [comment]
Here my edit, I test and is working!!

`public Action OnPlayerDeath(Event event, char [] name, bool dontBroadcast)
{
	if(GetConVarInt(g_Enabled) <= 0)
		return Plugin_Continue;
		
	int victim = GetClientOfUserId(GetEventInt(event, "userid"));   
	int attacker = GetClientOfUserId(GetEventInt(event, "attacker"));
	int assister = GetClientOfUserId(GetEventInt(event, "assister"));
	
	if(victim == attacker)
		return Plugin_Continue;
	
	char weapon[50];
	event.GetString("weapon", weapon, sizeof(weapon));
			
	Event newEvent = CreateEvent("player_death");
	newEvent.SetInt("userid", event.GetInt("userid"));
	newEvent.SetInt("attacker", event.GetInt("attacker"));
	newEvent.SetInt("assister", event.GetInt("assister"));
	newEvent.SetString("weapon", weapon);
	newEvent.SetBool("headshot", event.GetBool("headshot"));
	
	if(IsValidClient(attacker) && !IsFakeClient(attacker))
		newEvent.FireToClient(attacker);
		
	if(GetConVarInt(g_Victim) != 0 && IsValidClient(victim) && !IsFakeClient(victim))
		newEvent.FireToClient(victim);
		
	if(GetConVarInt(g_Assister) != 0 && IsValidClient(assister) && !IsFakeClient(assister))
		newEvent.FireToClient(assister);

	return Plugin_Handled;
}`

**Comment by abnerfs** [comment]
Good job: https://github.com/abnerfs/killfeed_filter/releases/tag/1.2

**Comment by ramonberrutti** [comment]
Hi, also add this to the new event:

`newEvent.SetInt("penetrated", event.GetInt("penetrated"));`

according with this table: https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events#player_death

also, you need to remove
```
	if(victim == attacker)
		return Plugin_Continue;
```

and change this:
```
	if(GetConVarInt(g_Victim) != 0 && IsValidClient(victim) && !IsFakeClient(victim))
		newEvent.FireToClient(victim);
```
to
```
	if(GetConVarInt(g_Victim) != 0 && attacker != victim && IsValidClient(victim) && !IsFakeClient(victim))
		newEvent.FireToClient(victim);
		
	if(GetConVarInt(g_Assister) != 0 && victim != assister && IsValidClient(assister) && !IsFakeClient(assister))
		newEvent.FireToClient(assister);
```

Suicide will now show only to that player and no to all.

**Comment by abnerfs** [comment]
Try v1.3 https://github.com/abnerfs/killfeed_filter/releases/tag/v1.3
