### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by ramonberrutti** [abnerfs/killfeed_filter#2]
Hi, I am here again!!

You need to put:

```
	newEvent.Cancel();
	return Plugin_Handled;
```

to prevent memory leak, Fire close the event, but FireToClient no.
https://sm.alliedmods.net/new-api/events/Event/FireToClient

**Comment by abnerfs** [comment]
Try v1.3 https://github.com/abnerfs/killfeed_filter/releases/tag/v1.3
