### ISSUE TITLE
Add client-side settings

### ISSUE THREAD

**Issue by Bucky21659** [abnerfs/killfeed_filter#3]
Hi, plugin looks great and from what it seems many have been wanting something like this for awhile, however as a player, only seeing my kills/deaths makes it feel kind of lonely. I don't mind it much when I'm on a full 20 player server, but if there's less than 12 or so players then definitely.

Some client side options to disable the filters would be nice, even if it's just an sm_cvar!

**Comment by abnerfs** [comment]
Try https://github.com/abnerfs/killfeed_filter/releases/tag/v1.4
