### ISSUE TITLE
[REQ] Admin cvar

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [abnerfs/killfeed_filter#4]
Any chance you could add a cvar that makes admins immune for this? My admins say they like to have the killfeed so they can spot aimbotters better. :)

**Comment by abnerfs** [comment]
I'll add an option to the players can disable feed filter.

**Comment by abnerfs** [comment]
Try: https://github.com/abnerfs/killfeed_filter/releases/tag/v1.4
